# Generated by Django 5.2.7 on 2025-10-24 11:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_preference',
            field=models.CharField(default='Window', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='passenger',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, to='flights.passenger'),
        ),
        migrations.AlterModelTable(
            name='passenger',
            table='passengers',
        ),
    ]
