# Generated by Django 5.2.7 on 2025-10-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(blank=True, max_length=20, null=True)),
                ('origin', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('total_seats', models.IntegerField(blank=True, null=True)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('airline_tier', models.CharField(blank=True, default='Standard', max_length=20, null=True)),
                ('demand_level', models.FloatField(blank=True, default=1.0, null=True)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_fare', models.FloatField()),
                ('seat_no', models.CharField(blank=True, max_length=5, null=True)),
                ('pnr', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.passenger')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
