# Generated by Django 5.2.7 on 2025-10-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='passenger',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
